name: Release Gem

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release to RubyGems
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Tests
        uses: ./.github/workflows/ruby_test.yml
        with:
          ruby-version: '3.4.2'

      - name: Build gem
        run: gem build ruby/simple_inline_text_annotation.gemspec

      - name: Publish to Rubygems
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: gem push ruby/simple_inline_text_annotation-*.gem
