name: Release Gem

on:
  workflow_dispatch:

jobs:
  run-tests:
    uses: ./.github/workflows/ruby_test.yml
    with:
      ruby-version: '3.4.2'

  release:
    name: Release to RubyGems
    needs: run-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build gem
        run: |
          cd ruby
          gem build simple_inline_text_annotation.gemspec

      - name: Publish to Rubygems
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          cd ruby
          gem push simple_inline_text_annotation-*.gem
