name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [3.4.2]
    name: RuboCop (Ruby ${{ matrix.ruby }})
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run RuboCop
        run: bundle exec rubocop

  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [3.4.2]
    name: RSpec (Ruby ${{ matrix.ruby }})
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run RSpec
        run: bundle exec rspec
