name: NPM

on:
  push:
    branches:
      - main
    paths:
      - 'js/**'

  pull_request:
    paths:
      - 'js/**'

jobs:
  test:
    uses: ./.github/workflows/npm_test.yml
    with:
      node-version: '20'
