name: Release Gem

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release to RubyGems
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.2

      - name: Build gem
        run: gem build simple_inline_text_annotation.gemspec

      - name: Publish to Rubygems
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: gem push simple_inline_text_annotation-*.gem
