name: Test Workflow

on:
  workflow_call:
    inputs:
      ruby-version:
        description: 'Ruby version to use'
        required: true
        type: string
      node-version:
        description: 'Node.js version to use'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ inputs.ruby-version }} and NPM ${{ inputs.node-version }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.ruby-version }}
          bundler-cache: true

      - name: Install Ruby dependencies
        run: |
          cd ruby
          bundle install

      - name: Run RuboCop
        run: |
          cd ruby
          bundle exec rubocop

      - name: Run RSpec
        run: |
          cd ruby
          bundle exec rspec

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install NPM dependencies
        run: |
          cd js
          npm ci

      - name: Run NPM tests
        run: |
          cd js
          npm run test
